; 8086 Assembly generated by NCC Compiler
bits 16
org 0x0

; Function: biosInitialize
_biosInitialize:
    ; Naked function - no prologue generated
    ; Inline assembly statement
    cli
    ; Inline assembly statement
    xor ax, ax
    ; Inline assembly statement
    mov ss, ax
    ; Inline assembly statement
    mov sp, 0x7C00
    ; Inline assembly statement
    sti
    ; Inline assembly statement
    jmp _main

_biosInitialize_exit:
    ; Naked function - no epilogue generated

; Function: main
_main:
    ; Naked function - no prologue generated
    ; Function call to clearScreen
    call _clearScreen
    ; Function call to randomString
    call _randomString
    ; Function call to writeChar
    mov ax, 65 ; Load literal
    push ax ; Argument 1
    call _writeChar
    add sp, 2 ; Remove arguments
    ; Function call to haltForever
    call _haltForever

_main_exit:
    ; Naked function - no epilogue generated

; Function: haltForever
_haltForever:
    ; Naked function - no prologue generated
    ; Inline assembly statement
    cli
    ; Inline assembly statement
    hlt
    ; Inline assembly statement
    jmp _haltForever

_haltForever_exit:
    ; Naked function - no epilogue generated

; Function: writeChar
_writeChar:
    push bp
    mov bp, sp

    ; Inline assembly statement
    mov al, [bp+4]
    ; Inline assembly statement
    mov ah, 0x0E
    ; Inline assembly statement
    mov bx, 0x0007
    ; Inline assembly statement
    int 0x10

_writeChar_exit:
    ; Standard function epilogue
    mov sp, bp
    pop bp
    ret

; Function: randomString
_randomString:
    push bp
    mov bp, sp

    ; Local variable declaration: str
    ; String literal: Hello, World!\n
    mov ax, string_0 ; Address of string
    push ax ; Initialize local variable
    ; Function call to writeChar
    mov ax, [bp-2] ; Load local variable str
    push ax ; Save left operand
    mov ax, 0 ; Load literal
    mov bx, ax ; Right operand to bx
    pop ax ; Restore left operand
    add ax, bx ; Addition
    ; Dereferencing pointer
    mov bx, ax ; Move address to BX
    cmp bx, 0 ; Check for null pointer
    je null_ptr_deref_0
    xor ah, ah ; Clear high byte for char
    mov al, [bx] ; Load byte (char) from memory
    jmp ptr_deref_end_0
null_ptr_deref_0:
    ; Null pointer dereference detected
    mov ax, 0 ; Return 0 for null deref
ptr_deref_end_0:
    push ax ; Argument 1
    call _writeChar
    add sp, 2 ; Remove arguments

_randomString_exit:
    ; Standard function epilogue
    mov sp, bp
    pop bp
    ret

; Function: clearScreen
_clearScreen:
    push bp
    mov bp, sp

    ; Inline assembly statement
    mov ax, 0x0003
    ; Inline assembly statement
    int 0x10

_clearScreen_exit:
    ; Standard function epilogue
    mov sp, bp
    pop bp
    ret

; String literals placed at _NCC_STRING_LOC
string_0: db 72, 101, 108, 108, 111, 44, 32, 87, 111, 114, 108, 100, 33, 10, 0  ; null terminator
; String literal location marker
__NCC_STRING_LOC:
; Array location marker
__NCC_ARRAY_LOC:
; Function: biosPadding
_biosPadding:
    ; Naked function - no prologue generated
    ; Inline assembly statement
    times 510 - ($ - $$) db 0
    ; Inline assembly statement
    dw 0xAA55

_biosPadding_exit:
    ; Naked function - no epilogue generated

