; 8086 Assembly generated by NCC Compiler
bits 16

; Function: main
_main:
    push bp
    mov bp, sp

    ; Return statement
    mov ax, 1 ; Load literal
    jmp _main_exit

_main_exit:
    ; Standard function epilogue
    mov sp, bp
    pop bp
    ret

