; 8086 Assembly generated by NCC Compiler
bits 16

; Function: main
_main:
    push bp
    mov bp, sp

    ; Local variable declaration: x
    mov ax, 22 ; Load literal
    push ax ; Initialize local variable
    ; If statement
    mov ax, [bp-2] ; Load local variable x
    push ax ; Save left operand
    mov ax, 22 ; Load literal
    mov bx, ax ; Right operand to bx
    pop ax ; Restore left operand
    cmp ax, bx ; Equal comparison
    mov ax, 0  ; Assume false
    je eq_true_2
    jmp eq_end_2
eq_true_2:
    mov ax, 1  ; Set true
eq_end_2:
    test ax, ax
    jz if_end1
    ; If true branch
    ; Return statement
    mov ax, 42 ; Load literal
    jmp _main_exit
if_end1:
    ; Return statement
    mov ax, 175 ; Load literal
    jmp _main_exit

_main_exit:
    ; Standard function epilogue
    mov sp, bp
    pop bp
    ret

